KENPOM_RAW_PATH = "../data/data/kenpom_raw/"
KENPOM_PROCESSED_PATH = "../data/data/kenpom_processed/"
KAGGLE_RAW_PATH = "../data/data/kaggle_raw/"
TOURNAMENT_MATRICES_PATH = "../data/data_matrices/tournament_matrices/"
TEAM_STATS_PATH = "../data/data_matrices/team_stats/"
TOURNAMENT_STATS_PATH = "../data/data_matrices/tournament_stats/"